"""Phase 0 — License plate image generator.

Generates a PNG license-plate image from a plate string. Used in Phase 3
to give each spawned vehicle a unique plate before rendering.

Usage (plain python, no blender):
    python scripts/gen_plate.py <plate_string> <output.png>
    python scripts/gen_plate.py --batch plates/ ["AB-123-CD","EF-456-GH"]

Plate style: white background, black text, EU-ish layout, ~520x110 px
(~0.52 m x 0.11 m at 1000 px/m). Returns the image path on success.
"""
from __future__ import annotations

import os
import sys
import random
import string

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    Image = ImageDraw = ImageFont = None


# plate dimensions in pixels (1000 px / metre)
PLATE_W_PX = 520
PLATE_H_PX = 110
BG = (255, 255, 255)
FG = (0, 0, 0)
BORDER = (40, 40, 40)

# default font: try a few common monospace fonts
_FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf",
]


def _load_font(size: int):
    if ImageFont is None:
        return None
    for path in _FONT_CANDIDATES:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                continue
    return ImageFont.load_default()


def render_plate(plate_str: str, out_path: str) -> str:
    """Render a plate PNG. If Pillow is unavailable (e.g. inside Blender's
    bundled python), generate a simple blank plate via bpy so we don't crash.
    Prefers Pillow (pre-generated by conda python) — call with an existing
    out_path first."""
    if os.path.exists(out_path):
        return out_path
    if Image is None:
        # Blender fallback: build a white image with the text drawn via imbuf
        try:
            return _render_plate_bpy(plate_str, out_path)
        except Exception as e:
            # last resort: blank white image
            try:
                import bpy
                img = bpy.data.images.new(os.path.basename(out_path), PLATE_W_PX, PLATE_H_PX)
                px = [255, 255, 255, 255] * (PLATE_W_PX * PLATE_H_PX)
                img.pixels.foreach_set(px) if hasattr(img.pixels, "foreach_set") else None
                # save
                img.filepath_raw = out_path
                img.file_format = "PNG"
                img.save_render(out_path)
                return out_path
            except Exception:
                raise RuntimeError("Cannot render plate (no Pillow, no bpy)")
    img = Image.new("RGB", (PLATE_W_PX, PLATE_H_PX), BG)
    draw = ImageDraw.Draw(img)
    # border
    draw.rectangle([0, 0, PLATE_W_PX - 1, PLATE_H_PX - 1], outline=BORDER, width=3)

    font = _load_font(int(PLATE_H_PX * 0.62))
    text = plate_str
    # measure
    try:
        bbox = draw.textbbox((0, 0), text, font=font)
        tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    except Exception:
        tw, th = font.getsize(text)
    x = (PLATE_W_PX - tw) / 2
    y = (PLATE_H_PX - th) / 2 - 2
    draw.text((x, y), text, fill=FG, font=font)

    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or ".", exist_ok=True)
    img.save(out_path)
    return out_path


def _render_plate_bpy(plate_str: str, out_path: str) -> str:
    """Fallback plate render using Blender's bpy (text via bpy.data.curves
    is heavy; we use a simple approach: create the image and write pixels
    with a rasterised text via freetype if available, else blank + name)."""
    import bpy
    img = bpy.data.images.new(os.path.basename(out_path), PLATE_W_PX, PLATE_H_PX)
    # blank white with black border
    px = []
    for y in range(PLATE_H_PX):
        for x in range(PLATE_W_PX):
            on_border = (x == 0 or y == 0 or x == PLATE_W_PX - 1 or y == PLATE_H_PX - 1)
            c = 0.15 if on_border else 1.0
            px.extend([c, c, c, 1.0])
    img.pixels = px
    img.filepath_raw = out_path
    img.file_format = "PNG"
    img.save()
    return out_path


def pregenerate_plates(plates: list, out_dir: str) -> list:
    """Pre-generate all plate PNGs (call from conda python which has Pillow)."""
    os.makedirs(out_dir, exist_ok=True)
    paths = []
    for p in plates:
        fn = "".join(c if c.isalnum() else "_" for c in p) + ".png"
        paths.append(render_plate(p, os.path.join(out_dir, fn)))
    return paths


def random_plate(rng: random.Random) -> str:
    """Generate a random plate like 'AB-123-CD'."""
    letters = string.ascii_uppercase
    a = "".join(rng.choices(letters, k=2))
    n = rng.randint(100, 999)
    b = "".join(rng.choices(letters, k=2))
    return f"{a}-{n}-{b}"


def main():
    args = sys.argv[1:]
    if not args:
        print("Usage: gen_plate.py <plate_string> <output.png>")
        print("       gen_plate.py --batch <out_dir> <plate1> <plate2> ...")
        sys.exit(1)
    if args[0] == "--batch":
        out_dir = args[1]
        plates = args[2:] if len(args) > 2 else [random_plate(random.Random()) for _ in range(10)]
        rng = random.Random(0)
        paths = []
        for p in plates:
            # sanitise filename
            fn = "".join(c if c.isalnum() else "_" for c in p) + ".png"
            paths.append(render_plate(p, os.path.join(out_dir, fn)))
        print("Generated", len(paths), "plates in", out_dir)
        for pth in paths:
            print(" ", pth)
        return
    plate_str = args[0]
    out_path = args[1] if len(args) > 1 else "plate.png"
    pth = render_plate(plate_str, out_path)
    print("Wrote", pth)


if __name__ == "__main__":
    main()
